// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfvncoawkwlrtbyhgtmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxmdm5jb2F3a3dscnRieWhndG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjU5NjMsImV4cCI6MjA2MjMwMTk2M30.5uxdraX9d5mU80zxdOwNfaVAs0XtVyYWFDseTF8p4EY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);